### ISSUE TITLE
Error: Cannot read properties of undefined (reading 'user')

### ISSUE THREAD

**Issue by Sahill17** [varunsridharan/action-hashnode-blog#13]
**Describe the bug**
After setting-up the workflow, while running the action, it stuck on the ERROR `Cannot read properties of undefined (reading 'user')`

**To Reproduce**
1. Go to 'Actions'
2. Click on 'Workflows'
3. Run workflow

**Expected behavior**
Running workflow successfully. 

**Screenshots**
![image](https://github.com/varunsridharan/action-hashnode-blog/assets/110122808/f945e9b5-0d63-4ebe-911e-bbee63249041)

**Desktop (please complete the following information):**
 - Windows 
 - Chrome

**Additional context**
Here is the YAML file
```
name: "Blog Updater"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs Every Day

jobs:
  update_blogs:
    name: "Update Blogs"
    runs-on: ubuntu-latest
    steps:
      - name: "Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "Hashnode Blogs"
        uses: "varunsridharan/action-hashnode-blog@main"
        with:
          USERNAME: 'Sahil17' # Hashnode Username
          BLOG_URL: 'https://operationsguy.hashnode.dev/' # Blog URL
          COUNT: 2 # MAX Visisble
          STYLE: "blog-alternate"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
Error and Warning 
![image](https://github.com/varunsridharan/action-hashnode-blog/assets/110122808/f90f1ab3-58ca-443e-8d63-11c0f1a314e3)
